[build-system]
requires = [
    "setuptools>=64",
    "wheel",
    "torch",
]
build-backend = "setuptools.build_meta"


[project]
name = "cumesh"
version = "1.0+hip"
description = "Native Windows HIP mesh utilities"
requires-python = ">=3.12"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Jianfeng Xiang", email = "belljig@outlook.com" }
]
dependencies = [
    "torch>=2.4.0",
    "tqdm",
]
